# Generated by Django 4.2.1 on 2023-06-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
